name = "UltraNest"
uuid = "6822f173-b0be-4018-9ee2-28bf56348d09"
version = "0.2.0"

[workspace]
projects = ["test", "docs"]

[deps]
CondaPkg = "992eb4ea-22a4-4c89-a5bb-47a3300528ab"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
CondaPkg = "0.2"
PythonCall = "0.9.26"
julia = "1.10"
